name: Create Spec
description: Creates a spec issue and updates the requirements issue status
inputs:
  final_output:
    description: 'JSON output from codex containing title and body'
    required: true
  repository:
    description: 'Repository in the format owner/repo'
    required: true
  requirements_issue_number:
    description: 'Requirements issue number to update'
    required: true
runs:
  using: node20
  main: dist/index.js
